files:
  - source: app/src/main/res/values/strings.xml
    translation: app/src/main/res/values-%android_code%/strings.xml
  - source: sdk-client/src/main/res/values/strings.xml
    translation: sdk-client/src/main/res/values-%android_code%/strings.xml
